from setuptools import setup, find_packages


setup(
    description='Simple but popular game in hangman',
    name='Hangman',
    version='0.1',
    packages=find_packages(),
    url='https://github.com/DawidLycz/Hungman',
    data_files=[
    ('data', [
    'databases/scoreboard.db', 
    'databases/settings.db',
    'fonts/font.ttf',
    'images/background.jpg',
    'images/background_2.jpg',
    'images/button_1.png', 
    'images/button_2.png',
    'images/button_3.png', 
    'images/gallow_0.png',
    'images/gallow_1.png', 
    'images/gallow_10.png',
    'images/gallow_11.png', 
    'images/gallow_12.png',
    'images/gallow_2.png', 
    'images/gallow_3.png',
    'images/gallow_4.png', 
    'images/gallow_5.png',
    'images/gallow_6.png', 
    'images/gallow_7.png',
    'images/gallow_8.png', 
    'images/gallow_9.png',
    'images/gallow_background.jpg', 
    'images/intro_background.jpg',
    'images/menu_background.jpg',
    'resolutions/1200_800.json', 
    'resolutions/1280_720.json',
    'resolutions/1920_1080.json', 
    'resolutions/800_600.json',
    'soundeffects/beep.mp3', 
    'soundeffects/correct.mp3',
    'soundeffects/error.mp3', 
    'soundeffects/game_over.mp3',
    'soundeffects/intro.mp3', 
    'soundeffects/music.mp3',
    'soundeffects/outro.mp3', 
    'soundeffects/success.mp3',
    'soundeffects/wrong.mp3',
    'text/english_key_words.json', 
    'text/english_strings.json',
    'text/polish_key_words.json', 
    'text/polish_strings.json'
    ])],
    license='MIT',
    author='Dawid Lycz',
    author_email='mamnie986@gmail.com',
    install_requires=[
        'pygame',
    ],
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Environment :: Other Environment',
        'Intended Audience :: Education',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
    ],
)


#setup(...,
    #   data_files=[('bitmaps', ['bm/b1.gif', 'bm/b2.gif']),
    #               ('config', ['cfg/data.cfg']),
    #  )
